
platform :ios, '8.0'

target 'Petroleum’ do
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension', '~> 3.0.10'
pod 'BaiduMapKit','~> 2.9.1' #百度地图SDK
pod 'IQKeyboardManager', '~> 5.0.0'
pod 'YBPopupMenu'
pod 'WHC_AutoLayoutKit'
pod 'MBProgressHUD', '~> 1.0.0'

end
